[WIP] Feature filter metatag
BenjaminMedia/wp-cxense pull request #12
Opened 2017-06-07 13:17 UTC by sulfo

2017-06-08 08:12 UTC, sulfo commented
Please wait to merge this until some documentation is written

2017-06-08 08:37 UTC, Frozire requested changes

2017-06-08 08:37 UTC, Frozire commented on src/Bonnier/WP/Cxense/Assets/Scripts.php
> +            foreach (get_the_tags() as $tag) {
Hvorfor ikke bruge den variable du lavede ovenover?

2017-06-08 10:07 UTC, sulfo commented on src/Bonnier/WP/Cxense/Assets/Scripts.php
> +            foreach (get_the_tags() as $tag) {
Det bliver lige rettet

2017-06-08 13:33 UTC, Frozire commented on src/Bonnier/WP/Cxense/Assets/Scripts.php
> +            $recs_tags['recs:articleid'] = $post->ID;
global $post, men bliver aldirg sat!?

2017-06-08 13:36 UTC, Frozire commented on src/Bonnier/WP/Cxense/Assets/Scripts.php
> +    private function recursive_get_meta_tag($recs_tags, $org_cxense_key = '')
ingen return?

2017-06-08 13:38 UTC, Frozire commented on src/Bonnier/WP/Cxense/Assets/Scripts.php
> +            $cat = get_category($catid);
$catid?

2017-06-08 19:53 UTC, sulfo commented on src/Bonnier/WP/Cxense/Assets/Scripts.php
> +            $recs_tags['recs:articleid'] = $post->ID;
Den er sat per default. Det sådan Wordpress fungere :)
https://codex.wordpress.org/Function_Reference/$post

2017-06-08 19:53 UTC, sulfo commented on src/Bonnier/WP/Cxense/Assets/Scripts.php
> +            $cat = get_category($catid);
Det hermed ændret til noget som giver bedre mening

2017-06-09 07:53 UTC, Frozire commented on src/Bonnier/WP/Cxense/Assets/Scripts.php
> +        $catParent = null;
CamelCase

2017-06-09 08:15 UTC, Frozire approved these changes

2017-06-09 08:15 UTC, merged